# Generated by Django 2.2.5 on 2019-09-25 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('killboard', '0002_scopes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alliance',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('alliance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='char_alliance', to='killboard.Alliance')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('alliance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='killboard.Alliance')),
            ],
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShipType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SolarSystem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('security_status', models.FloatField(null=True)),
                ('security_class', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='corporation', to='killboard.ShipType')),
            ],
        ),
        migrations.CreateModel(
            name='Killmail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('km_date', models.DateTimeField()),
                ('items_dict', models.TextField()),
                ('pos_x', models.FloatField()),
                ('pos_y', models.FloatField()),
                ('pos_z', models.FloatField()),
                ('damage_taken', models.IntegerField()),
                ('moon', models.IntegerField(null=True)),
                ('war', models.IntegerField(null=True)),
                ('attackers_dict', models.TextField()),
                ('alliance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='alliance', to='killboard.Alliance')),
                ('attackers', models.ManyToManyField(related_name='attackers', to='killboard.Character')),
                ('comments', models.ManyToManyField(related_name='comments', to='killboard.Comment')),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='corporation', to='killboard.Corporation')),
                ('faction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='faction', to='killboard.Faction')),
                ('ship_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ship', to='killboard.Ship')),
                ('solar_system', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='solar_system', to='killboard.SolarSystem')),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='victim', to='killboard.Character')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='corporation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='char_corporation', to='killboard.Corporation'),
        ),
    ]
