# Generated by Django 2.2.5 on 2019-09-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('killboard', '0002_scopes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Killmail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('km_date', models.DateTimeField()),
                ('solar_system', models.IntegerField()),
                ('items_dict', models.TextField()),
                ('pos_x', models.FloatField()),
                ('pos_y', models.FloatField()),
                ('pos_z', models.FloatField()),
                ('ship_type', models.IntegerField()),
                ('damage_taken', models.IntegerField()),
                ('moon', models.IntegerField(null=True)),
                ('war', models.IntegerField(null=True)),
                ('victim', models.IntegerField()),
                ('alliance', models.IntegerField(null=True)),
                ('corporation', models.IntegerField(null=True)),
                ('faction', models.IntegerField(null=True)),
                ('attackers_dict', models.TextField()),
            ],
        ),
    ]
