# Generated by Django 2.2.5 on 2019-10-03 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('killboard', '0005_auto_20190929_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attacker',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='killboard.Character'),
        ),
    ]
