# Generated by Django 2.2.6 on 2019-10-13 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('killboard', '0006_auto_20191004_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attacker',
            name='weapon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='killboard.ItemType'),
        ),
    ]
