# Generated by Django 2.2.6 on 2019-10-21 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('killboard', '0007_auto_20191013_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='allianceallies',
            name='name',
            field=models.CharField(default='HelloWorld', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characterallies',
            name='name',
            field=models.CharField(default='HelloWorld', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corporationallies',
            name='name',
            field=models.CharField(default='HelloWorld', max_length=100),
            preserve_default=False,
        ),
    ]
